import sys
from pathlib import Path
import argparse
import shutil
from typing import Any, cast

import matplotlib.pyplot as plt
import numpy as np

sys.path.append("/scratchsan/observatorio/juagudeloo/MUISCA/")

from utils.modest_data import ModestData
from utils.cache_manage import ModestDataCache
from utils.modest_data import transform_modest_stokes_profiles


PLAGE_CROP_BOUNDS = (0, 100, 400, 600)  # X_MIN, X_MAX, Y_MIN, Y_MAX


# -----------------------------------------------------------------------------
# Distribution analysis helpers
# - build output paths
# - copy precomputed training artifacts
# - reshape MODEST data for plotting
# - render MODEST histograms and stokes summaries
# -----------------------------------------------------------------------------
def _output_root(cropped_region: bool, crop_label: str) -> Path:
    # Keep distribution outputs grouped under the same MODEST whole/cropped tree.
    base = Path("/scratchsan/observatorio/juagudeloo/MUISCA/images/analysis/modest")
    if cropped_region:
        label = crop_label.strip()
        if not label:
            raise ValueError("--crop-label must be non-empty when --cropped-region is set")
        return base / "cropped" / label / "distributions"
    return base / "whole" / "distributions"


def _experiment_root_dir(experiment_root: str) -> Path:
    root = Path("/scratchsan/observatorio/juagudeloo/MUISCA/output/experiments") / experiment_root
    if not root.exists():
        raise FileNotFoundError(f"Experiment root not found: {root}")
    return root


def _resolve_training_artifact(experiment_dir: Path, filename: str) -> Path | None:
    direct = experiment_dir / filename
    if direct.exists():
        return direct
    matches = sorted(experiment_dir.glob(f"**/{filename}"))
    if matches:
        return matches[0]
    return None


def _copy_training_artifacts(experiment_dir: Path, distribution_target: str, out_root: Path) -> None:
    # These files are generated by the training script; this mode just reuses them.
    mhd_files = [
        "training_data_histograms_train_split_per_tau_T.png",
        "training_data_histograms_train_split_per_tau_Vz.png",
        "training_data_histograms_train_split_per_tau_Bz.png",
    ]
    stokes_files = [
        "training_data_histograms_train_split_stokes_mean_std_profiles.png",
    ]

    if distribution_target in ("mhd", "both"):
        mhd_out = out_root / "MHD"
        mhd_out.mkdir(parents=True, exist_ok=True)
        for name in mhd_files:
            src = _resolve_training_artifact(experiment_dir, name)
            if src is None:
                print(f"Warning: could not find training artifact: {name}")
                continue
            shutil.copy2(src, mhd_out / name)
            print(f"Copied training artifact: {src} -> {mhd_out / name}")

    if distribution_target in ("stokes", "both"):
        stokes_out = out_root / "stokes"
        stokes_out.mkdir(parents=True, exist_ok=True)
        for name in stokes_files:
            src = _resolve_training_artifact(experiment_dir, name)
            if src is None:
                print(f"Warning: could not find training artifact: {name}")
                continue
            shutil.copy2(src, stokes_out / name)
            print(f"Copied training artifact: {src} -> {stokes_out / name}")


def _reshape_prediction_stokes(prediction_stokes: dict[str, np.ndarray]) -> np.ndarray:
    # MODEST prediction Stokes are assumed to already be continuum-normalized.
    nx, ny = prediction_stokes["I"].shape[:2]
    I_flat = prediction_stokes["I"].reshape(nx * ny, -1)
    V_flat = prediction_stokes["V"].reshape(nx * ny, -1)
    return np.stack([I_flat, V_flat], axis=1).astype(np.float32)


def _to_wavelength_array(wl_obj) -> np.ndarray:
    if wl_obj is None:
        raise ValueError("MODEST wavelength metadata is missing; cannot generate Stokes distribution plot")
    if hasattr(wl_obj, "value"):
        wl = np.asarray(wl_obj.value, dtype=np.float64)
    else:
        wl = np.asarray(wl_obj, dtype=np.float64)
    if wl.ndim != 1:
        raise ValueError(f"Expected 1D wavelength array, got shape {wl.shape}")
    return wl


def _plot_modest_stokes_mean_std(
    stokes_input: np.ndarray,
    wavelengths: np.ndarray,
    out_path: Path,
) -> None:
    # Compute per-wavelength mean/std over all pixels so the profile shape is easy to compare.
    arr = np.asarray(stokes_input, dtype=np.float32)
    if arr.ndim != 3 or arr.shape[1] != 2:
        raise ValueError(f"Expected stokes_input with shape (N, 2, n_wl), got {arr.shape}")

    wl = np.asarray(wavelengths, dtype=np.float64)
    if wl.ndim != 1 or wl.size != arr.shape[2]:
        raise ValueError(f"Wavelength shape mismatch: expected ({arr.shape[2]},), got {wl.shape}")

    I_norm = arr[:, 0, :]
    V_norm = arr[:, 1, :]

    I_mean_norm = np.mean(I_norm, axis=0)
    I_std_norm = np.std(I_norm, axis=0)
    V_mean_norm = np.mean(V_norm, axis=0)
    V_std_norm = np.std(V_norm, axis=0)

    I_mean = I_mean_norm
    I_std = I_std_norm
    V_mean = V_mean_norm
    V_std = V_std_norm

    fig, axes = plt.subplots(2, 1, figsize=(10, 7), sharex=True)
    fig.suptitle("MODEST | Stokes Profiles: mean ± 1σ", fontsize=13, fontweight="bold")

    axes[0].plot(wl, I_mean, color="tab:orange", linewidth=1.8, label="Mean I")
    axes[0].fill_between(wl, I_mean - I_std, I_mean + I_std, color="tab:orange", alpha=0.25, label="±1σ")
    axes[0].set_ylabel("Stokes I")
    axes[0].grid(True, alpha=0.25)
    axes[0].legend(loc="best", fontsize=9)

    axes[1].plot(wl, V_mean, color="tab:purple", linewidth=1.8, label="Mean V")
    axes[1].fill_between(wl, V_mean - V_std, V_mean + V_std, color="tab:purple", alpha=0.25, label="±1σ")
    axes[1].set_xlabel("Wavelength [Angstrom]")
    axes[1].set_ylabel("Stokes V")
    axes[1].grid(True, alpha=0.25)
    axes[1].legend(loc="best", fontsize=9)

    out_path.parent.mkdir(parents=True, exist_ok=True)
    fig.tight_layout(rect=(0, 0, 1, 0.95))
    fig.savefig(out_path, dpi=170, bbox_inches="tight")
    plt.close(fig)
    print(f"Saved MODEST stokes distribution plot: {out_path}")


def _nearest_tau_key(param_cube: dict[float, np.ndarray], tau_value: float) -> float:
    # Match requested tau values to the closest available atmospheric node.
    keys = [float(k) for k in param_cube.keys()]
    if tau_value in param_cube:
        return tau_value
    for key in keys:
        if np.isclose(key, tau_value, atol=1e-6, rtol=0.0):
            return key
    idx = int(np.argmin(np.abs(np.asarray(keys, dtype=np.float64) - float(tau_value))))
    return keys[idx]


def _plot_modest_mhd_histograms(spinor_atm: dict[str, dict[float, np.ndarray]], tau_values: list[float], out_dir: Path) -> None:
    # Make one histogram panel per atmospheric variable: T, Vlos, and Blos.
    mapping = [
        ("T", "T", "tab:red"),
        ("Vlos", "Vlos", "tab:blue"),
        ("Blos", "Blos", "tab:green"),
    ]

    n_tau = len(tau_values)
    n_cols = min(4, max(1, n_tau))
    n_rows = int(np.ceil(n_tau / n_cols))

    out_dir.mkdir(parents=True, exist_ok=True)

    for source_key, filename_key, color in mapping:
        if source_key not in spinor_atm:
            print(f"Warning: MODEST atmospheric key not found: {source_key}")
            continue

        fig, axes = plt.subplots(n_rows, n_cols, figsize=(4.2 * n_cols, 3.0 * n_rows), squeeze=False)
        for i, tau in enumerate(tau_values):
            ax = axes[i // n_cols][i % n_cols]
            tau_key = _nearest_tau_key(spinor_atm[source_key], float(tau))
            arr = np.asarray(spinor_atm[source_key][tau_key], dtype=np.float32)
            vals = arr[np.isfinite(arr)].ravel()

            if vals.size == 0:
                ax.text(0.5, 0.5, "No finite data", ha="center", va="center", transform=ax.transAxes)
                ax.set_axis_off()
                continue

            p1, p50, p99 = np.percentile(vals, [1, 50, 99])
            ax.hist(vals, bins=120, color=color, alpha=0.7)
            ax.axvline(p1, color="black", linestyle="--", linewidth=1.0)
            ax.axvline(p50, color="goldenrod", linestyle="-", linewidth=1.0)
            ax.axvline(p99, color="black", linestyle="--", linewidth=1.0)
            ax.set_title(f"log(tau)={float(tau):.2f} | n={vals.size}")
            ax.grid(True, alpha=0.2)

        for j in range(n_tau, n_rows * n_cols):
            axes[j // n_cols][j % n_cols].set_axis_off()

        fig.suptitle(f"MODEST {source_key} distributions per optical depth", fontsize=13, fontweight="bold")
        fig.tight_layout(rect=(0, 0, 1, 0.95))
        out_path = out_dir / f"modest_histograms_per_tau_{filename_key}.png"
        fig.savefig(out_path, dpi=170, bbox_inches="tight")
        plt.close(fig)
        print(f"Saved MODEST MHD histogram panel: {out_path}")


def main(args):
    # Resolve where the new distribution outputs should be written.
    out_root = _output_root(cropped_region=args.cropped_region, crop_label=args.crop_label)
    out_root.mkdir(parents=True, exist_ok=True)

    # Locate the experiment folder whose training artifacts should be copied into this run.
    experiment_dir = _experiment_root_dir(args.experiment_root)

    # MODEST data loader handles continuum-normalized Stokes and atmospheric tau cubes.
    modest = ModestData(
        circular_polarization_threshold=args.polarization_threshold,
        stokes_v_multiplier=args.modest_stokes_v_multiplier,
    )
    modest_cache = ModestDataCache(cache_dir=args.modest_cache_dir)
    if args.clear_modest_cache:
        modest_cache.clear(confirm=False)

    # Build the prediction input grid used by the analysis view.
    prediction_input_mode = "downsampled" if args.downsample_prediction_input else "upsampled"
    region_bounds = tuple(args.crop_bounds) if args.cropped_region else None
    modest_data = cast(dict[str, Any], modest.load_all(
        region_bounds=region_bounds,
        apply_mask=args.polarization_mask,
        cache=modest_cache,
        use_cache=True,
        prediction_input_mode=prediction_input_mode,
    ))

    if args.distribution_target in ("stokes", "both"):
        # Save the MODEST stokes profile summary.
        stokes_out = out_root / "stokes"
        prediction_stokes = modest_data.get("prediction_stokes", modest_data.get("smoothed_stokes", None))
        if not isinstance(prediction_stokes, dict):
            raise ValueError("MODEST prediction stokes are missing; cannot generate stokes distributions")
        wl = _to_wavelength_array(modest_data.get("wl", None))
        prediction_stokes = transform_modest_stokes_profiles(
            stokes=prediction_stokes,
            wavelength_angstrom=wl,
            shift_positions=float(args.modest_stokes_shift_positions),
            i_scale=float(args.modest_stokes_i_scale),
            v_scale=float(args.modest_stokes_v_scale),
            invert_direction=bool(args.modest_stokes_invert_direction),
        )
        stokes_input = _reshape_prediction_stokes(prediction_stokes)
        _plot_modest_stokes_mean_std(
            stokes_input=stokes_input,
            wavelengths=wl,
            out_path=stokes_out / "modest_stokes_mean_std_profiles.png",
        )

    if args.distribution_target in ("mhd", "both"):
        # Save the MODEST atmospheric histograms across all available tau nodes.
        mhd_out = out_root / "MHD"
        spinor_atm_obj = modest_data.get("spinor_atm", None)
        if not isinstance(spinor_atm_obj, dict):
            raise ValueError("MODEST spinor_atm data is missing; cannot generate MHD distributions")
        spinor_atm = cast(dict[str, dict[float, np.ndarray]], spinor_atm_obj)
        tau_values_raw = modest_data.get("tau_values", sorted(spinor_atm.get("T", {}).keys()))
        if not isinstance(tau_values_raw, (list, tuple, np.ndarray)):
            tau_values_raw = sorted(spinor_atm.get("T", {}).keys())
        tau_values = [float(v) for v in tau_values_raw]
        _plot_modest_mhd_histograms(spinor_atm=spinor_atm, tau_values=tau_values, out_dir=mhd_out)

    # Reuse the corresponding training-run artifacts so this folder mirrors the experiment output.
    _copy_training_artifacts(
        experiment_dir=experiment_dir,
        distribution_target=args.distribution_target,
        out_root=out_root,
    )

    print(f"Finished distributions analysis in: {out_root}")


if __name__ == "__main__":
    # CLI for selecting which distribution artifacts to generate and where to place them.
    parser = argparse.ArgumentParser(description="Generate MODEST and training distribution artifacts")
    parser.add_argument("--cropped-region", action="store_true", help="Use cropped MODEST region")
    parser.add_argument(
        "--crop-bounds",
        nargs=4,
        type=int,
        default=PLAGE_CROP_BOUNDS,
        metavar=("X_MIN", "X_MAX", "Y_MIN", "Y_MAX"),
        help=f"Bounds for cropping the region (default: {PLAGE_CROP_BOUNDS})",
    )
    parser.add_argument("--crop-label", type=str, default="plage", help="Subfolder label for cropped outputs")
    parser.add_argument("--polarization-mask", action="store_true", help="Apply polarization mask")
    parser.add_argument(
        "--polarization-threshold",
        type=float,
        default=1e-2,
        help="Threshold for circular polarization mask",
    )
    parser.add_argument(
        "--distribution-target",
        choices=["stokes", "mhd", "both"],
        default="both",
        help="Distribution artifact target",
    )
    parser.add_argument(
        "--experiment-root",
        type=str,
        default="experiment_80_to_113",
        help="Experiment folder under output/experiments",
    )
    parser.add_argument(
        "--modest-cache-dir",
        type=str,
        default="/scratchsan/observatorio/juagudeloo/MUISCA/.modest_cache",
        help="MODEST cache directory",
    )
    parser.add_argument("--clear-modest-cache", action="store_true", help="Clear MODEST cache before loading")
    parser.add_argument(
        "--downsample-prediction-input",
        action="store_true",
        help="Use downsampled prediction input grid instead of upsampled",
    )
    parser.add_argument(
        "--modest-stokes-v-multiplier",
        type=float,
        default=-1.0,
        help="Multiplier applied to MODEST Stokes V during loading",
    )
    parser.add_argument(
        "--modest-stokes-shift-positions",
        type=float,
        default=0.0,
        help="Shift MODEST Stokes profiles by this many spectral sample positions (default: 0.0)",
    )
    parser.add_argument(
        "--modest-stokes-i-scale",
        type=float,
        default=1.0,
        help="Multiply MODEST Stokes I profiles by this factor after optional shift/inversion (default: 1.0)",
    )
    parser.add_argument(
        "--modest-stokes-v-scale",
        type=float,
        default=1.0,
        help="Multiply MODEST Stokes V profiles by this factor after optional shift/inversion (default: 1.0)",
    )
    parser.add_argument(
        "--modest-stokes-invert-direction",
        action="store_true",
        help="Invert MODEST Stokes profile direction along the spectral axis before optional shift/scale",
    )

    main(parser.parse_args())
